# Generated by Django 4.1.4 on 2022-12-23 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=50)),
                ('posted', models.DateField()),
                ('url', models.TextField()),
                ('note', models.TextField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
